---
- name: install alacritty
  pacman:
    name: alacritty
  become: true

- name: create alacritty configuration directory
  file:
    dest: /home/{{ archlinux_username }}/.config/alacritty
    state: directory
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0755
  become: true

- name: configure alacritty
  template:
    src: alacritty.yml
    dest: /home/{{ archlinux_username }}/.config/alacritty/alacritty.yml
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644
  become: true

- name: configure alacritty
  template:
    src: dracula.yml
    dest: /home/{{ archlinux_username }}/.config/alacritty/dracula.yml
    owner: "{{ archlinux_username }}"
    group: users
    mode: 0644
  become: true
