- name: install fcitx5
  pacman:
    name:
      - fcitx5-im
      - fcitx5-chinese-addons
      - fcitx5-nord
      - fcitx5-pinyin-zhwiki
  become: true

- name: configure fcitx5 environment
  lineinfile:
    path: /etc/environment
    line: "{{ item }}"
  with_items:
    - "# Fcitx5 Configuration"
    - "GTK_IM_MODULE=fcitx"
    - "QT_IM_MODULE=fcitx"
    - "XMODIFIERS=@im=fcitx"
    - "INPUT_METHOD=fcitx"
  become: true
